# Generated by Django 5.2.5 on 2025-09-12 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        # CreateModel operations for Destino, Itinerario and Paquete were
        # removed because the initial migration (0001_initial.py) already
        # defines those models. Keeping only field alterations and relation
        # additions to avoid attempting to recreate existing tables.
        # Removed legacy index/field removals that conflict with the current
        # initial migration state. Those operations targeted fields that
        # are not present in `0001_initial.py` and caused project_state errors
        # during makemigrations. Keeping this migration focused on adding
        # Destino/Itinerario/Paquete and related fields.
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='catalogo.categoria'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        # Relationship fields for Paquete (categoria, destinos, itinerario)
        # were already created in the initial migration (0001_initial.py).
        # Removing AddField operations to prevent duplicate through-table
        # creation (catalogo_paquete_destinos, catalogo_paquete_itinerario).
    ]
