# Generated by Django 5.2.6 on 2025-09-12 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_seed_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('dias', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dia', models.IntegerField()),
                ('titulo', models.CharField(max_length=255)),
                ('actividades', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('descripcion_corta', models.TextField()),
                ('descripcion_completa', models.TextField()),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=2)),
                ('numero_reseñas', models.IntegerField()),
                ('precio', models.CharField(max_length=100)),
                ('precio_original', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=100)),
                ('max_personas', models.IntegerField()),
                ('dificultad', models.CharField(max_length=100)),
                ('imagenes', models.JSONField()),
                ('incluido', models.JSONField()),
                ('no_incluido', models.JSONField()),
                ('fechas_disponibles', models.JSONField()),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.categoria')),
                ('destinos', models.ManyToManyField(to='catalogo.destino')),
                ('itinerario', models.ManyToManyField(to='catalogo.itinerario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
