# Generated by Django 5.2.6 on 2025-09-15 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_destino_itinerario_paquete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('PORCENTAJE', 'PORCENTAJE'), ('FIJO', 'FIJO')], max_length=12)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicioDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prioridad', models.PositiveSmallIntegerField(default=10, help_text='1 = mayor prioridad')),
                ('exclusivo', models.BooleanField(default=True, help_text='Si es True, corta la cadena de descuentos')),
                ('estado', models.BooleanField(default=True)),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicio_descuentos', to='descuentos.descuento')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_descuento', to='catalogo.servicio')),
            ],
            options={
                'db_table': 'descuentos_servicio_descuento',
                'ordering': ('prioridad', '-id'),
                'unique_together': {('servicio', 'descuento')},
            },
        ),
    ]
